# Generated by Django 3.0.4 on 2021-12-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.TimeField(max_length=15, null=True),
        ),
    ]
