# Generated by Django 3.0.4 on 2021-12-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0003_history_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_table_failure_data',
        ),
    ]
