# Generated by Django 3.0.4 on 2021-12-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0007_temp_table_failure_data_temp_table_failuredata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_table_failure_data',
        ),
        migrations.DeleteModel(
            name='temp_table_FailureData',
        ),
    ]
