# Generated by Django 3.0.4 on 2025-03-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsunit',
            name='average_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pbsunit',
            name='chk_average_speed',
            field=models.FloatField(default=0),
        ),
    ]
