# Generated by Django 3.0.4 on 2021-11-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assetRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Asset Register',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='failuredata',
            name='failure_type',
            field=models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('random', 'Random')], default='safety', max_length=600),
        ),
    ]
