# Generated by Django 3.0.4 on 2021-11-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0003_auto_20211109_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_type',
            new_name='user_role',
        ),
    ]
