# Generated by Django 3.0.4 on 2021-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0004_auto_20211109_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsmaster',
            name='MTBR',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_disable',
            field=models.IntegerField(default=0),
        ),
    ]
