# Generated by Django 3.0.4 on 2021-11-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0005_auto_20211111_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmaster',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.Product'),
        ),
    ]
