# Generated by Django 3.0.4 on 2021-11-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0007_pbsmaster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.IntegerField(default=0),
        ),
    ]
