# Generated by Django 3.0.4 on 2021-11-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0008_auto_20211112_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
    ]
