# Generated by Django 3.0.4 on 2021-11-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0009_asset_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuredata',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
