# Generated by Django 3.0.4 on 2021-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0010_auto_20211115_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuremode',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='failuremode',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
