# Generated by Django 3.0.4 on 2021-11-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0011_auto_20211115_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFailureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(blank=True, max_length=550)),
                ('failure_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('event_description', models.CharField(max_length=600, null=True)),
                ('mode_description', models.CharField(blank=True, max_length=600, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(max_length=15, null=True)),
                ('detection', models.CharField(max_length=600, null=True)),
                ('service_delay', models.IntegerField(default=0)),
                ('immediate_investigation', models.TextField(blank=True, null=True)),
                ('failure_type', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('random', 'Random')], default='safety', max_length=600)),
                ('safety_failure', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=60)),
                ('hazard_id', models.CharField(blank=True, max_length=60, null=True)),
                ('cm_description', models.TextField(blank=True, null=True)),
                ('replaced_asset_config_id', models.CharField(max_length=500, null=True)),
                ('cm_start_date', models.DateField(blank=True, null=True)),
                ('cm_start_time', models.TimeField(max_length=15, null=True)),
                ('cm_end_date', models.DateField(max_length=15, null=True)),
                ('cm_end_time', models.TimeField(max_length=15, null=True)),
                ('oem_failure_reference', models.TextField(blank=True, null=True)),
                ('P_id', models.IntegerField(default=0)),
                ('asset_config_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.Asset', to_field='asset_config_id')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.Defect')),
                ('mode_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.FailureMode')),
            ],
            options={
                'verbose_name_plural': 'Failure data Collection Form',
            },
        ),
    ]
