# Generated by Django 3.0.4 on 2021-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0012_tempfailuredata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempfailuredata',
            name='mode_id',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
