# Generated by Django 3.0.4 on 2021-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0013_auto_20211116_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defect',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
