# Generated by Django 3.0.4 on 2021-11-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0014_auto_20211118_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempFailureData',
        ),
    ]
