# Generated by Django 3.0.4 on 2021-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0016_auto_20211119_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
