# Generated by Django 3.0.4 on 2021-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0017_auto_20211119_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewboard',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewboard',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
