# Generated by Django 3.0.4 on 2021-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0018_auto_20211120_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectdiscussion',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='fracas.UserProfile'),
        ),
    ]
