# Generated by Django 3.0.4 on 2021-11-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0021_auto_20211122_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectdiscussion',
            name='attd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.UserProfile'),
        ),
        migrations.AlterField(
            model_name='defectdiscussion',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='fracas.EmployeeMaster'),
        ),
    ]
