# Generated by Django 3.0.4 on 2021-11-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0023_auto_20211122_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectDiscussion1',
            fields=[
                ('defect_discussion_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_date', models.DateField(auto_now_add=True, null=True)),
                ('attd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.UserProfile')),
                ('attendees', models.ManyToManyField(blank=True, null=True, to='fracas.EmployeeMaster')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.Defect')),
                ('review_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fracas.ReviewBoard')),
            ],
        ),
    ]
