# Generated by Django 3.0.4 on 2021-11-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0024_defectdiscussion1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='defect_discussion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.DefectDiscussion1'),
        ),
        migrations.AlterField(
            model_name='defectdiscussion1',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='fracas.EmployeeMaster'),
        ),
    ]
