# Generated by Django 3.0.4 on 2021-11-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0025_auto_20211122_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectdiscussion',
            name='attd',
        ),
        migrations.AlterField(
            model_name='action',
            name='defect_discussion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.DefectDiscussion'),
        ),
        migrations.DeleteModel(
            name='DefectDiscussion1',
        ),
    ]
