# Generated by Django 3.0.4 on 2021-11-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0028_auto_20211122_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectdiscussion',
            name='sample',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
