# Generated by Django 3.0.4 on 2021-11-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0029_defectdiscussion_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctiveaction',
            name='P_id',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='defectdiscussion',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='reviewboard',
            name='P_id',
        ),
        migrations.RemoveField(
            model_name='reviewboard',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='defectdiscussion',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='fracas.EmployeeMaster'),
        ),
    ]
