# Generated by Django 3.0.4 on 2021-11-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0030_auto_20211122_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewboard',
            name='P_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewboard',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
