# Generated by Django 3.0.4 on 2021-11-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0031_auto_20211122_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectdiscussion',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
