# Generated by Django 3.0.4 on 2021-11-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0032_defectdiscussion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
