# Generated by Django 3.0.4 on 2021-11-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0033_employeemaster_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemaster',
            name='description',
        ),
    ]
