# Generated by Django 3.0.4 on 2021-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0034_remove_employeemaster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectdiscussion',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='fracas.UserProfile'),
        ),
    ]
