# Generated by Django 3.0.4 on 2021-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0035_auto_20211122_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_table_import_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField()),
                ('subsystem', models.TextField()),
                ('subsystem_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_description', models.TextField()),
                ('asset_type', models.TextField()),
                ('asset_description', models.TextField()),
                ('MTBF', models.FloatField()),
                ('MTBSAF', models.FloatField()),
                ('MTBR', models.FloatField()),
                ('MART', models.FloatField()),
                ('asset_quantity', models.IntegerField()),
                ('error_list', models.TextField()),
                ('updated_by', models.TextField()),
            ],
        ),
    ]
