# Generated by Django 3.0.4 on 2021-12-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0036_temp_table_import_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_table_import_file',
            name='product_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
