# Generated by Django 3.0.4 on 2021-12-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0037_auto_20211207_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_table_asset_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_config_id', models.CharField(max_length=50, unique=True)),
                ('asset_serial_number', models.CharField(max_length=20)),
                ('location_id', models.TextField()),
                ('location_description', models.TextField()),
                ('asset_type', models.TextField()),
                ('asset_type_id', models.TextField()),
                ('software_version', models.CharField(max_length=15)),
                ('asset_description', models.TextField()),
                ('software_description', models.TextField()),
                ('asset_status', models.CharField(max_length=15)),
                ('is_active', models.IntegerField(default=0)),
                ('P_id', models.IntegerField(default=0)),
                ('error_list', models.TextField()),
                ('updated_by', models.TextField()),
            ],
        ),
    ]
