# Generated by Django 3.0.4 on 2021-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0038_temp_table_asset_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_table_asset_register',
            name='P_id',
            field=models.TextField(),
        ),
    ]
