# Generated by Django 3.0.4 on 2021-12-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0040_temp_table_failuredata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_table_asset_register',
            name='asset_config_id',
            field=models.CharField(max_length=50),
        ),
    ]
