# Generated by Django 3.0.4 on 2021-12-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0041_auto_20211209_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_table_failuredata',
            name='updated_by',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
