# Generated by Django 3.0.4 on 2021-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0043_auto_20211209_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_table_failure_mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_id', models.TextField()),
                ('mode_description', models.TextField()),
                ('asset_type', models.TextField()),
                ('asset_type_id', models.TextField()),
                ('P_id', models.TextField()),
                ('updated_by', models.TextField()),
            ],
        ),
    ]
