# Generated by Django 3.0.4 on 2021-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0044_temp_table_failure_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_table_failure_mode',
            name='error_list',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
