# Generated by Django 3.1.6 on 2021-12-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0047_auto_20211220_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_table_import_file',
            old_name='MTBR',
            new_name='MTTR',
        ),
        migrations.AddField(
            model_name='pbsmaster',
            name='availability_target',
            field=models.IntegerField(default=0),
        ),
    ]
