# Generated by Django 3.1.6 on 2021-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0048_auto_20211220_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MTBF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='MTBSAF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='MTTR',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='availability_target',
            field=models.IntegerField(default=0),
        ),
    ]
