# Generated by Django 3.1.6 on 2021-12-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0049_auto_20211220_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
