# Generated by Django 3.1.6 on 2021-12-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0051_pbsunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbsunit',
            old_name='name',
            new_name='MTBFMTBSAF',
        ),
        migrations.RenameField(
            model_name='pbsunit',
            old_name='unit',
            new_name='MTTR',
        ),
    ]
