# Generated by Django 3.1.6 on 2022-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0052_auto_20211221_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmaster',
            name='availability_target',
            field=models.FloatField(default=0),
        ),
    ]
