# Generated by Django 3.1.6 on 2022-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0053_auto_20220105_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability_target',
            field=models.FloatField(default=0),
        ),
    ]
