# Generated by Django 3.1.6 on 2022-01-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0055_auto_20220110_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_description',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_owner',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_status',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='action',
            name='progress_log',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_config_id',
            field=models.CharField(max_length=550, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_serial_number',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='asset',
            name='software_version',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='corrective_action_status',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_status',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='defectdiscussion',
            name='description',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='designation',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='employee_id',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='name',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='failuredata',
            name='hazard_id',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='failuredata',
            name='safety_failure',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=550),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='mode_description',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='failuremode',
            name='mode_id',
            field=models.CharField(max_length=550, unique=True),
        ),
        migrations.AlterField(
            model_name='reviewboard',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='reviewboard',
            name='meeting_outcome',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='reviewboard',
            name='meeting_status',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='root_cause_status',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='temp_table_asset_register',
            name='asset_config_id',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='temp_table_asset_register',
            name='asset_serial_number',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='temp_table_asset_register',
            name='asset_status',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='temp_table_asset_register',
            name='software_version',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='temp_table_import_file',
            name='product_id',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
