# Generated by Django 3.1.6 on 2022-01-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0056_auto_20220110_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuredata',
            name='failure_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='failuredata',
            name='service_delay',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_table_failure_data',
            name='failure_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
