# Generated by Django 3.1.6 on 2022-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0057_auto_20220110_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuredata',
            name='failure_id',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='failuredata',
            name='service_delay',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
