# Generated by Django 3.1.6 on 2022-01-11 04:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0058_auto_20220110_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuremode',
            name='asset_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=list, size=None),
        ),
    ]
