# Generated by Django 3.1.6 on 2022-01-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0059_auto_20220111_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcause',
            name='defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.defect'),
        ),
    ]
