# Generated by Django 3.1.6 on 2022-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0060_auto_20220112_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmaster',
            name='MART',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pbsmaster',
            name='MTBSAF',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pbsmaster',
            name='MTTR',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pbsmaster',
            name='availability_target',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
