# Generated by Django 3.1.6 on 2022-01-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0061_auto_20220113_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbsmaster',
            name='MTTR',
            field=models.FloatField(blank=True),
        ),
    ]
