# Generated by Django 3.0.4 on 2022-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0066_auto_20220117_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcause',
            name='root_cause_description',
            field=models.TextField(),
        ),
    ]
