# Generated by Django 3.0.4 on 2022-01-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0067_auto_20220118_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuredata',
            name='cm_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='failuredata',
            name='cm_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
