# Generated by Django 3.0.4 on 2022-01-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0068_auto_20220119_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='progress_log',
            field=models.TextField(),
        ),
    ]
