# Generated by Django 3.1.6 on 2022-02-15 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0071_history_function_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System', models.CharField(blank=True, max_length=550)),
                ('MTBF', models.FloatField(default=0)),
                ('MTBSAF', models.FloatField(default=0)),
                ('MTTR', models.FloatField(default=0)),
                ('availability_target', models.FloatField(default=0)),
                ('is_active', models.IntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fracas.product')),
            ],
        ),
    ]
