# Generated by Django 3.0.4 on 2025-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0072_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsunit',
            name='average_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pbsunit',
            name='chk_average_speed',
            field=models.FloatField(default=0),
        ),
    ]
