# Generated by Django 3.0.4 on 2025-03-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0073_auto_20250305_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_trains',
            field=models.IntegerField(default=0),
        ),
    ]
