# Generated by Django 3.2.25 on 2025-06-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0003_product_num_of_trains'),
        ('fracas', '0074_product_num_of_trains'),
    ]

    operations = [
    ]
