# Generated by Django 3.2.25 on 2025-06-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0075_merge_20250616_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sub_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='TO_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='department',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='kilometre_reading',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='location_id',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='no_of_trip_cancel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='reported_to_PPIO',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='sel_car',
            field=models.TextField(blank=True, null=True),
        ),
    ]
