# Generated by Django 3.2.25 on 2025-06-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0076_auto_20250616_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuredata',
            name='incident',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
