# Generated by Django 3.2.25 on 2025-06-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0077_failuredata_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuredata',
            name='deboarding',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
