# Generated by Django 3.2.25 on 2025-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0079_jobcardids'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_set_no', models.CharField(blank=True, max_length=550, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=550, null=True)),
                ('subsystem', models.CharField(blank=True, max_length=550)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('nature_of_job', models.TextField(blank=True, null=True)),
                ('sic_required', models.TextField(blank=True, null=True)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Job Card',
            },
        ),
    ]
