# Generated by Django 3.2.25 on 2025-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0080_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='job_card_no',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
