# Generated by Django 3.2.25 on 2025-06-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0081_jobcard_job_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='failure_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.failuredata'),
        ),
    ]
