# Generated by Django 3.2.25 on 2025-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0083_jobcard_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='completion_time',
            field=models.TimeField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='delay_to_service',
            field=models.TimeField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='event_time',
            field=models.TimeField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='from_revenue_service',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='issued_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='ohe_required',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='trip_no',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
