# Generated by Django 3.2.25 on 2025-06-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0085_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='sic_no',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
