# Generated by Django 3.2.25 on 2025-06-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0086_jobcard_sic_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='job_card_id',
        ),
        migrations.DeleteModel(
            name='JobCard',
        ),
        migrations.DeleteModel(
            name='JobDetails',
        ),
    ]
