# Generated by Django 3.2.25 on 2025-06-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0087_auto_20250618_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_set_no', models.CharField(blank=True, max_length=550, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=550, null=True)),
                ('subsystem', models.CharField(blank=True, max_length=550)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('nature_of_job', models.TextField(blank=True, null=True)),
                ('sic_required', models.TextField(blank=True, null=True)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('job_card_no', models.CharField(blank=True, max_length=550)),
                ('run_status', models.IntegerField(default=0)),
                ('ohe_required', models.CharField(blank=True, max_length=550)),
                ('issued_to', models.TextField(blank=True, null=True)),
                ('completion_time', models.CharField(blank=True, max_length=550)),
                ('from_revenue_service', models.CharField(blank=True, max_length=550)),
                ('delay_to_service', models.CharField(blank=True, max_length=550)),
                ('trip_no', models.CharField(blank=True, max_length=550)),
                ('event_date', models.DateField(null=True)),
                ('event_time', models.TimeField(max_length=15, null=True)),
                ('sic_no', models.CharField(blank=True, max_length=550)),
                ('failure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.failuredata')),
            ],
            options={
                'verbose_name_plural': 'Job Card',
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('job_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_no', models.CharField(blank=True, max_length=550, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('job_card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Job details',
            },
        ),
    ]
