# Generated by Django 3.2.25 on 2025-06-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0088_jobcard_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='issued_by',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='l1_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='l1_time',
            field=models.TimeField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='signature_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
