# Generated by Django 3.2.25 on 2025-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0089_auto_20250618_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='l2_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='l2_time',
            field=models.TimeField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='received_by',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='signature_img2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
