# Generated by Django 3.2.25 on 2025-06-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0090_auto_20250618_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkToMaintainers',
            fields=[
                ('job_work_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobwork_name', models.CharField(blank=True, max_length=550, null=True)),
                ('jobwork_work', models.TextField(blank=True, null=True)),
                ('jobwork_signature', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('job_card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Job work',
            },
        ),
    ]
