# Generated by Django 3.2.25 on 2025-06-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0091_jobworktomaintainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='follow_up_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='handed_over',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='new_supervisor',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='signature_img3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
