# Generated by Django 3.2.25 on 2025-06-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0092_auto_20250619_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReplacedEquipment',
            fields=[
                ('job_equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('jobequipment_name', models.CharField(blank=True, max_length=550, null=True)),
                ('jobequipment_new_no', models.CharField(blank=True, max_length=550, null=True)),
                ('jobequipment_old_no', models.CharField(blank=True, max_length=550, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('job_card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Job Replaced Equipment',
            },
        ),
    ]
