# Generated by Django 3.2.25 on 2025-06-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0094_auto_20250619_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='completion_date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='completion_date_time2',
            field=models.TimeField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='completion_name2',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='corrective_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='down_time2',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sic_has_performed',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='sic_start_time',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='signature_img5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='train_can_be_energized2',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='train_can_be_moved2',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
