# Generated by Django 3.2.25 on 2025-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0095_auto_20250619_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='details_of_the_activitues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
