# Generated by Django 3.2.25 on 2025-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0096_jobcard_details_of_the_activitues'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='close_name',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='close_time',
            field=models.TimeField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='signature_img6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
