# Generated by Django 3.2.25 on 2025-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0097_auto_20250619_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureDataIDs',
            fields=[
                ('uid_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=550, null=True)),
                ('month', models.CharField(blank=True, max_length=550, null=True)),
                ('last_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Failure Data IDs',
            },
        ),
    ]
