# Generated by Django 3.2.25 on 2025-06-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0098_failuredataids'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIRIDs',
            fields=[
                ('uid_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=550, null=True)),
                ('last_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'EIR IDs',
            },
        ),
    ]
