# Generated by Django 3.2.25 on 2025-06-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0099_eirids'),
    ]

    operations = [
        migrations.CreateModel(
            name='RIRGeneration',
            fields=[
                ('eir_id', models.AutoField(primary_key=True, serialize=False)),
                ('depot', models.CharField(blank=True, max_length=550, null=True)),
                ('addressed_by', models.TextField(blank=True, null=True)),
                ('incident_details', models.TextField(blank=True, null=True)),
                ('repercussion', models.TextField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=550, null=True)),
                ('incident_time', models.CharField(blank=True, max_length=550, null=True)),
                ('failure_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.failuredata')),
            ],
            options={
                'verbose_name_plural': 'EIR',
            },
        ),
    ]
