# Generated by Django 3.2.25 on 2025-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0100_rirgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirgeneration',
            name='eir_gen_id',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
