# Generated by Django 3.2.25 on 2025-06-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0101_rirgeneration_eir_gen_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RIRGeneration',
            new_name='EIRGeneration',
        ),
    ]
