# Generated by Django 3.2.25 on 2025-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0102_rename_rirgeneration_eirgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eirgeneration',
            name='component',
            field=models.TextField(blank=True, null=True),
        ),
    ]
