# Generated by Django 3.2.25 on 2025-06-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0103_eirgeneration_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationDetails',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('non_compliance_details', models.TextField(blank=True, null=True)),
                ('onvestigation_details', models.TextField(blank=True, null=True)),
                ('relevant_ERTS_clause', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('eir_dt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.eirgeneration')),
            ],
            options={
                'verbose_name_plural': 'Job details',
            },
        ),
    ]
