# Generated by Django 3.2.25 on 2025-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0104_investigationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='eirgeneration',
            name='action_taken_in_depot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eirgeneration',
            name='concern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eirgeneration',
            name='further_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
