# Generated by Django 3.2.25 on 2025-06-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0105_auto_20250624_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIRImages',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
                ('eir_dt_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.eirgeneration')),
            ],
            options={
                'verbose_name_plural': 'EIR Images',
            },
        ),
    ]
