# Generated by Django 3.2.25 on 2025-06-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0106_eirimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='eirgeneration',
            name='TRSL',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='eirgeneration',
            name='signature_img2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eirgeneration',
            name='signature_img3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
