# Generated by Django 3.2.25 on 2025-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0107_auto_20250625_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='KilometreReading',
            fields=[
                ('km_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('ts01_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts02_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts03_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts04_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts05_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts06_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts07_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts08_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts09_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts10_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts11_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts12_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts13_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts14_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts15_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts16_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts17_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts18_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts19_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts20_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts21_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts22_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts23_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts24_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts25_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts26_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts27_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts28_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts29_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts30_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts31_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts32_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts33_tkm', models.CharField(blank=True, max_length=550, null=True)),
                ('ts34_tkm', models.CharField(blank=True, max_length=550, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kilometre Reading',
            },
        ),
    ]
