# Generated by Django 3.2.25 on 2025-07-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0108_kilometrereading'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcause',
            name='material_is_damaged',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='organistaional_management_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rootcause',
            name='systemic_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='immediate_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='leading_reasons',
            field=models.TextField(blank=True),
        ),
    ]
