# Generated by Django 3.2.25 on 2025-07-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0109_auto_20250702_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRIDs',
            fields=[
                ('uid_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=550, null=True)),
                ('last_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'NCR IDs',
            },
        ),
        migrations.CreateModel(
            name='NCRGeneration',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('ncr_gen_id', models.CharField(blank=True, max_length=550, null=True)),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('is_active', models.IntegerField(default=0)),
                ('rootcause_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fracas.rootcause')),
            ],
            options={
                'verbose_name_plural': 'NCR',
            },
        ),
    ]
