# Generated by Django 3.2.25 on 2025-07-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0110_ncrgeneration_ncrids'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='action_date',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='approved_date',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='corrective_action_date',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='defect_date',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='fnl_date',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='verification_date',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
