# Generated by Django 3.2.25 on 2025-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0111_auto_20250709_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='defect_time',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
