# Generated by Django 3.2.25 on 2025-07-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0112_ncrgeneration_defect_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='defect_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
