# Generated by Django 3.2.25 on 2025-07-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0113_ncrgeneration_defect_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='assembly_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='assembly_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='detection_workstation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='drawing_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='green_red_channel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='inspector_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='location_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='sel_car',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='serial_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
