# Generated by Django 3.2.25 on 2025-07-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0114_auto_20250709_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='assembly_name',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='assembly_no',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='detection_workstation',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='drawing_no',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='green_red_channel',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='inspector_name',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='sel_car',
        ),
        migrations.RemoveField(
            model_name='ncrgeneration',
            name='serial_no',
        ),
    ]
