# Generated by Django 3.2.25 on 2025-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0116_auto_20250709_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='chkCritical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='chkMajor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='chkMinor',
            field=models.IntegerField(default=0),
        ),
    ]
