# Generated by Django 3.2.25 on 2025-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0117_auto_20250709_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='defect_detected_by',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='defect_detected_workstation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='defect_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='defect_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='no_of_defective_parts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='no_of_parts_deloverd',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='specification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='supplier_name',
            field=models.TextField(blank=True),
        ),
    ]
