# Generated by Django 3.2.25 on 2025-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0118_auto_20250709_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='active_deviations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='chk_Internal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='chk_Supplier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='chk_TWL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='chk_Transportation',
            field=models.IntegerField(default=0),
        ),
    ]
