# Generated by Django 3.2.25 on 2025-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0119_auto_20250709_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='notok_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='ok_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='signature_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='signature_img2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='signature_img3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='signature_img4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='signature_img5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
