# Generated by Django 3.2.25 on 2025-07-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0120_auto_20250709_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='action_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='approved_by',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='approved_designation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='attachments_files',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='containment_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='corrective_action_by',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='corrective_action_designation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='detection',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='effectiveness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='initial_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='inp_root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='invoice_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='non_conforming_part_disposition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='occurrence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='responsibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='responsible_for_execution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='verification_name',
            field=models.TextField(blank=True),
        ),
    ]
