# Generated by Django 3.2.25 on 2025-07-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0121_auto_20250709_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='cost_1',
            field=models.CharField(default=0, max_length=550),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='cost_2',
            field=models.CharField(default=0, max_length=550),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='cost_3',
            field=models.CharField(default=0, max_length=550),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='cost_4',
            field=models.CharField(default=0, max_length=550),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='cost_5',
            field=models.CharField(default=0, max_length=550),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='cost_6',
            field=models.CharField(default=0, max_length=550),
        ),
        migrations.AddField(
            model_name='ncrgeneration',
            name='total_cost',
            field=models.CharField(default=0, max_length=550),
        ),
    ]
