# Generated by Django 3.2.25 on 2025-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0123_auto_20250709_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSerialNumberIDs',
            fields=[
                ('uid_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.CharField(blank=True, max_length=550, null=True)),
                ('location_id', models.CharField(blank=True, max_length=550, null=True)),
                ('sub_location', models.CharField(blank=True, max_length=550, null=True)),
                ('last_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Asset Serial Number IDs',
            },
        ),
    ]
