# Generated by Django 3.2.25 on 2025-07-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0124_assetserialnumberids'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='asset_type',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
