# Generated by Django 3.2.25 on 2025-07-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0125_ncrgeneration_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='ncr_status',
            field=models.IntegerField(default=0),
        ),
    ]
