# Generated by Django 3.2.25 on 2025-07-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0126_ncrgeneration_ncr_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRImagesList',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('ncr_gen_id', models.CharField(blank=True, max_length=550, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'NCR Images List',
            },
        ),
    ]
