# Generated by Django 3.2.25 on 2025-07-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0128_ncrgeneration_root_cause_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='rev_no',
            field=models.CharField(default=0, max_length=550),
        ),
    ]
