# Generated by Django 3.2.25 on 2025-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0129_ncrgeneration_rev_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsunit',
            name='num_of_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='pbsunit',
            name='running_time',
            field=models.IntegerField(default=18),
        ),
    ]
