# Generated by Django 3.2.25 on 2025-08-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0130_auto_20250801_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcause',
            name='assembly_no',
            field=models.TextField(blank=True),
        ),
    ]
