# Generated by Django 3.2.25 on 2025-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0131_rootcause_assembly_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='rejection_status',
            field=models.IntegerField(default=0),
        ),
    ]
