# Generated by Django 3.2.25 on 2025-08-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0132_ncrgeneration_rejection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
