# Generated by Django 3.2.25 on 2025-08-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0133_ncrgeneration_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncrgeneration',
            name='accept_status',
            field=models.IntegerField(default=0),
        ),
    ]
