# Generated by Django 3.2.25 on 2025-08-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0134_ncrgeneration_accept_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcause',
            name='failure_detection',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
