# Generated by Django 3.2.25 on 2025-08-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0135_rootcause_failure_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emp_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
