# Generated by Django 3.2.25 on 2025-08-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0136_auto_20250806_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuredata',
            name='affecting_failures',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='revenue_service_delay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
