# Generated by Django 3.2.25 on 2025-08-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0137_auto_20250806_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuredata',
            name='dept_location',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='failuredata',
            name='failure_category',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
