# Generated by Django 3.2.25 on 2025-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0138_auto_20250806_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='issued_signature',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
