# Generated by Django 3.2.25 on 2025-08-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0139_jobcard_issued_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='received_by_signature',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
