# Generated by Django 3.2.25 on 2025-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0140_jobcard_received_by_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='new_supervisor_id',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='new_supervisor_signature',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
