# Generated by Django 3.2.25 on 2025-08-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0141_auto_20250807_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='completion_signature',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
