# Generated by Django 3.2.25 on 2025-08-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0142_jobcard_completion_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='completion_signature2',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
