# Generated by Django 3.2.25 on 2025-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0143_jobcard_completion_signature2'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='close_name_signature',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
