# Generated by Django 3.2.25 on 2025-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0144_jobcard_close_name_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='sic_start_date',
            field=models.DateField(null=True),
        ),
    ]
