# Generated by Django 3.2.25 on 2025-08-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0145_jobcard_sic_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbsunit',
            name='criteria_delay_for_saf',
            field=models.IntegerField(default=3),
        ),
    ]
