# Generated by Django 3.2.25 on 2025-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0146_pbsunit_criteria_delay_for_saf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeMaintenanceLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('dt_sc', models.CharField(blank=True, max_length=550, null=True)),
                ('dt_opm', models.CharField(blank=True, max_length=550, null=True)),
                ('dt_cm', models.CharField(blank=True, max_length=550, null=True)),
            ],
        ),
    ]
