# Generated by Django 3.2.25 on 2025-09-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0147_downtimemaintenancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimemaintenancelog',
            name='date',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
