# Generated by Django 3.2.25 on 2025-09-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fracas', '0148_alter_downtimemaintenancelog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimemaintenancelog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
