# Generated by Django 3.0.4 on 2021-12-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fracas_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_table_import_file',
        ),
    ]
